
export const NEW_USER = 'NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';



export const NEW_FLASH_MESSAGE = 'NEW_FLASH_MESSAGE'




export const ACCOUNT_SETTINGS = 'ACCOUNT_SETTINGS'
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE'


 export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
 export const FETCH_ITEMS = 'FETCH_ITEMS'


 export const FETCH_ORDERS = 'FETCH_ORDERS';
 export const FETCH_ORDERS_DETAILS = 'FETCH_ORDERS_DETAILS';
 export const FETCH_CUSTOMER_DETAILS = 'FETCH_CUSTOMER_DETAILS';


 export const FETCH_LATEST_STATUS = 'FETCH_LATEST_STATUS'


 export const NOTIFICATION_ADD = 'NOTIFICATION_ADD'